#define BOOLEAN 1
#define ELSE 2
#define IMPLEMENTS 3
#define PRINTLN 4
#define VOID 5
#define BREAK 6
#define EXTENDS 7
#define INT 8
#define READLN 9
#define WHILE 10
#define CLASS 11
#define FOR 12
#define INTERFACE 13
#define RETURN 14
#define DOUBLE 15
#define IF 16
#define NEWARRAY 17
#define STRING 18
#define BCTRUE 19
#define BCFALSE 20
#define ID 21

#define LESSEQUAL 22
#define NOTEQUAL 23
#define ASSIGNOP 24
#define LEFTPAREN 25
#define LEFTBRACE 26
#define STRINGCONSTANT 27
#define DIVISION 28
#define GREATER 29
#define AND 30
#define SEMICOLON 31
#define RIGHTPAREN 32
#define RIGHTBRACE 33
#define PLUS 34
#define MOD 35
#define GREATEREQUAL 36
#define OR 37
#define COMMA 38
#define LEFTBRACKET 39
#define INTCONSTANT 40
#define MULTIPLICATION 41
#define MINUS 42
#define LESS 43
#define EQUAL 44
#define NOT 45
#define PERIOD 46
#define RIGHTBRACKET 47
#define DOUBLECONSTANT 48
#define BOOLEANCONSTANT 49
